runtime: python27
api_version: 1
threadsafe: true
service: default

libraries:
- name: webapp2
  version: "latest"

handlers:
- url: /cloud-datastore-export
  script: cloud_datastore_admin.app
  login: admin
